default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "staging", "--branch", "dev"]
      - id: mixed-line-ending
      - id: end-of-file-fixer
        exclude: '(\.sql|\.out)$' # These need te be formatted very particularly for pg_regress
      - id: trailing-whitespace
        exclude: '(\.sql|\.out)$' # These need te be formatted very particularly for pg_regress
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: check-yaml
        exclude: "charts/paradedb/" # Exclude all files in the charts/paradedb/ directory, which aren't standard YAML
      - id: check-json
      - id: check-xml
      - id: check-ast
      - id: check-toml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
        exclude: '\.rs$' # This doesn't play well with #![allow(clippy::crate_in_macro_def)]
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: debug-statements
      - id: destroyed-symlinks
      - id: fix-encoding-pragma
      - id: fix-byte-order-marker
      - id: requirements-txt-fixer

  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args: ["--indent-size", "2"]

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        exclude: "charts/paradedb/" # Exclude all files in the charts/paradedb/ directory, which aren't standard YAML

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.51.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin@^6.7.5"
          - "eslint@8.49.0"
          - "eslint-config-next@13.4.19"
          - "eslint-config-prettier@^9.0.0"
          - "eslint-plugin-prettier@^5.0.0"
          - "eslint-plugin-unused-imports@^3.0.0"
          - "prettier@^3.0.3"

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
      - id: cargo-check

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.0.1
    hooks:
      - id: pylint

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length=100"]
