{{- if .Values.cluster.backup.scheduled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "cluster.name" . }}-backup
spec:
  suspend: {{ .Values.cluster.backup.scheduled.suspend }}
  immediate: {{ .Values.cluster.backup.scheduled.immediate }}
  schedule: {{ .Values.cluster.backup.scheduled.schedule }}
  backupOwnerReference: {{ .Values.cluster.backup.scheduled.backupOwnerReference }}
  method: {{ .Values.cluster.backup.scheduled.method }}
  cluster:
    name: {{ include "cluster.name" . }}
{{- end }}
