apiVersion: v1
kind: ConfigMap
metadata:
  name: bootstrap-sql
data:
  bootstrap.sql: |
    \c paradedb\
    CREATE EXTENSION IF NOT EXISTS pg_bm25 CASCADE;
    CREATE EXTENSION IF NOT EXISTS pg_search CASCADE;
    CREATE EXTENSION IF NOT EXISTS pgnodemx CASCADE;
    CREATE EXTENSION IF NOT EXISTS pg_cron CASCADE;
    CREATE EXTENSION IF NOT EXISTS pg_net CASCADE;
    CREATE EXTENSION IF NOT EXISTS pg_ivm CASCADE;
    CREATE EXTENSION IF NOT EXISTS pg_graphql CASCADE;
    CREATE EXTENSION IF NOT EXISTS pg_hashids CASCADE;
    CREATE EXTENSION IF NOT EXISTS pg_jsonschema CASCADE;
    CREATE EXTENSION IF NOT EXISTS pg_repack CASCADE;
    CREATE EXTENSION IF NOT EXISTS pg_stat_monitor CASCADE;
    CREATE EXTENSION IF NOT EXISTS pg_hint_plan CASCADE;
    CREATE EXTENSION IF NOT EXISTS pg_roaringbitmap CASCADE;
    CREATE EXTENSION IF NOT EXISTS pgfaceting CASCADE;
    CREATE EXTENSION IF NOT EXISTS pgml CASCADE;
    CREATE EXTENSION IF NOT EXISTS pgtap CASCADE;
    CREATE EXTENSION IF NOT EXISTS pgvector CASCADE;
    CREATE EXTENSION IF NOT EXISTS pgaudit CASCADE;
    CREATE EXTENSION IF NOT EXISTS postgis CASCADE;
    CREATE EXTENSION IF NOT EXISTS pgrouting CASCADE;
    CREATE EXTENSION IF NOT EXISTS http CASCADE;
    CREATE EXTENSION IF NOT EXISTS hypopg CASCADE;
    CREATE EXTENSION IF NOT EXISTS rum CASCADE;
    CREATE EXTENSION IF NOT EXISTS age CASCADE;
