apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql
data:
  init.sql: |
    \c {{ default .Release.Name .Values.name }}
    GRANT CREATE ON SCHEMA public TO "{{ default .Release.Name .Values.name }}";