apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Release.Name }}-cluster
  {{- with .Values.metadata.labels }}
  labels:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.metadata.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  dockerImage: {{ .Values.spec.dockerImage }}
  teamId: {{ .Values.spec.teamId }}
  numberOfInstances: {{ .Values.spec.numberOfInstances }}
  users: {{ toYaml .Values.spec.users | nindent 4 }}
  {{- with .Values.spec.usersWithSecretRotation }}
  usersWithSecretRotation: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.spec.usersWithInPlaceSecretRotation }}
  usersWithInPlaceSecretRotation: {{ toYaml . | nindent 4 }}
  {{- end }}
  enableMasterLoadBalancer: {{ .Values.spec.enableMasterLoadBalancer }}
  enableReplicaLoadBalancer: {{ .Values.spec.enableReplicaLoadBalancer }}
  enableConnectionPooler: {{ .Values.spec.enableConnectionPooler }}
  enableReplicaConnectionPooler: {{ .Values.spec.enableReplicaConnectionPooler }}
  enableMasterPoolerLoadBalancer: {{ .Values.spec.enableMasterPoolerLoadBalancer }}
  enableReplicaPoolerLoadBalancer: {{ .Values.spec.enableReplicaPoolerLoadBalancer }}
  allowedSourceRanges: {{ toYaml .Values.spec.allowedSourceRanges | nindent 4 }}
  databases: {{ toYaml .Values.spec.databases | nindent 4 }}
  preparedDatabases: {{ toYaml .Values.spec.preparedDatabases | nindent 4 }}
  postgresql:
    version: "{{ .Values.spec.postgresql.version }}"
    parameters: {{ toYaml .Values.spec.postgresql.parameters | nindent 6 }}
  {{- with .Values.spec.env }}
  env:
{{ toYaml . | indent 4 }}
  {{- end }}
  volume:
    size: {{ .Values.spec.volume.size }}
  {{- with .Values.spec.additionalVolumes }}
  additionalVolumes:
{{ toYaml . | indent 4 }}
  {{- end }}
  enableShmVolume: {{ .Values.spec.enableShmVolume }}
  resources: {{ toYaml .Values.spec.resources | nindent 4 }}
  patroni: {{ toYaml .Values.spec.patroni | nindent 4 }}
  {{- with .Values.spec.initContainers }}
  initContainers:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.spec.sidecars }}
  sidecars:
{{ toYaml . | indent 4 }}
  {{- end }}
  tls: {{ toYaml .Values.spec.tls | nindent 4 }}
  {{- with .Values.spec.nodeAffinity }}
  nodeAffinity:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.spec.streams }}
  streams:
{{ toYaml . | indent 4 }}
  {{- end }}