{{- if .Values.search.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "search.configMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "search.labels" . | nindent 4 }}
data:
    API_KEY: {{ .Values.search.security.apiKey }}
    OPENSEARCH_HOST: {{ .Values.opensearchCluster.general.serviceName }}
    OPENSEARCH_PORT: {{ .Values.opensearchCluster.general.httpPort |  default "9200" | quote }}
    OPENSEARCH_USER: {{ .Values.opensearchCluster.security.user }}
    OPENSEARCH_PASSWORD: {{ .Values.opensearchCluster.security.password }}
    OPENSEARCH_USE_TLS: {{ .Values.opensearchCluster.security.tls.enabled | default "true" | quote }}
    PGSYNC_HOST: {{ include "sync.fullname" . }}
    PGSYNC_PORT: {{ .Values.sync.service.port | default "7433" | quote }}
    PGSYNC_SSL_ENABLED: {{ .Values.sync.security.tls | default "false" | quote }}
{{- end }}
