apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "search.fullname" . }}
  labels:
    {{- include "search.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.search.replicaCount }}
  selector:
    matchLabels:
      {{- include "search.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.search.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "search.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.search.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "search.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.search.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.search.securityContext | nindent 12 }}
          image: "{{ .Values.search.image.repository }}:{{ .Values.search.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.search.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.search.service.port }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name:  {{ include "search.configMapName" . }}
          resources:
            {{- toYaml .Values.search.resources | nindent 12 }}
      {{- with .Values.search.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.search.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.search.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
