{{- if .Values.pgsync.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sync.serviceAccountName" . }}
  labels:
    {{- include "sync.labels" . | nindent 4 }}
  {{- with .Values.pgsync.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
