# workflows/lint-markdown.yml
#
# Markdown: Linting
# Lint Markdown files using Prettier.

name: Linting

on:
  pull_request:
    paths:
      - "**.md"
      - "**/**.md"
      - ".github/**/**.md"
      - ".github/workflows/lint-markdown.yml"
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: lint-markdown-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up NodeJS Environment
        uses: actions/setup-node@v3

      # We have to use npm install -g here, as the yarn
      # equivalent "yarn global add" doesn't correctly
      # add the command to the path in GitHub Actions.
      - name: Install Prettier
        run: npm install -g prettier

      - name: Check if Markdown files are Formatted
        run: prettier --check '**/**.md' # Prettier glob syntax hits all .md files with this
